import whoosh.fields


class Schema(whoosh.fields.SchemaClass):

    game = whoosh.fields.STORED()
    document_type = whoosh.fields.TEXT(phrase=False, stored=True)
    faction = whoosh.fields.STORED()
    name = whoosh.fields.NGRAMWORDS(stored=True)
    book = whoosh.fields.STORED()
    page = whoosh.fields.STORED()
    Type = whoosh.fields.STORED()
    Range = whoosh.fields.STORED()
    S = whoosh.fields.STORED()
    D = whoosh.fields.STORED()
    Abilities = whoosh.fields.STORED()
    AP = whoosh.fields.STORED()
    A = whoosh.fields.STORED()
    BS = whoosh.fields.STORED()
    WS = whoosh.fields.STORED()
    Ld = whoosh.fields.STORED()
    M = whoosh.fields.STORED()
    Max = whoosh.fields.STORED()
    S = whoosh.fields.STORED()
    T = whoosh.fields.STORED()
    Sv = whoosh.fields.STORED()
    W = whoosh.fields.STORED()
    Description = whoosh.fields.STORED()
    PsychicPower = whoosh.fields.STORED()
    Ability = whoosh.fields.STORED()
    Details = whoosh.fields.STORED()
    WarpCharge = whoosh.fields.STORED()
    Effect = whoosh.fields.STORED()
    Deny = whoosh.fields.STORED()
    Manifest = whoosh.fields.STORED()
    PowersKnown = whoosh.fields.STORED()
